Repository PSLmodels/Tax-Calculator, pull requests merged in 2018-04, with the labels that each got.

#1950 Add Calculator class distribution_table_dataframe method
  taxcalc/calculate.py
  taxcalc/tbi/tbi.py
  taxcalc/tests/test_utils.py
  taxcalc/utils.py
Labels: ready

#1954 Add two optional arguments to Policy implement_reform method
  taxcalc/policy.py
  taxcalc/taxcalcio.py
  taxcalc/tbi/tbi.py
  taxcalc/tests/test_calculate.py
  taxcalc/tests/test_policy.py
Labels: ready

#1955 Clarify validation of _BE_subinc_wrt_earnings parameter value
  taxcalc/behavior.py
Labels: ready

#1958 Handle pycodestyle (formerly pep8) warnings
  taxcalc/simpletaxio.py
  taxcalc/tests/test_compatible_data.py
  taxcalc/tests/test_taxcalcio.py
  taxcalc/tests/test_utils.py
  taxcalc/utils.py
Labels: ready

#1960 Strengthen type checking of reform parameters
  taxcalc/policy.py
  taxcalc/tests/test_calculate.py
  taxcalc/tests/test_policy.py
Labels: ready

#1952 Apply Policy parameter processing/validation logic to Behavior class
  taxcalc/behavior.json
  taxcalc/behavior.py
  taxcalc/calculate.py
  taxcalc/parameters.py
  taxcalc/policy.py
  taxcalc/taxcalcio.py
  taxcalc/tbi/tbi.py
  taxcalc/tests/test_behavior.py
  taxcalc/tests/test_calculate.py
  taxcalc/tests/test_parameters.py
  taxcalc/tests/test_policy.py
  taxcalc/tests/test_reforms.py
  taxcalc/tests/test_tbi.py
Labels: WIP

#1971 Cosmetic revisions to handle pylint warnings
  taxcalc/behavior.py
  taxcalc/calculate.py
  taxcalc/parameters.py
  taxcalc/policy.py
  taxcalc/records.py
  taxcalc/tests/test_behavior.py
  taxcalc/tests/test_cpscsv.py
  taxcalc/tests/test_parameters.py
Labels: in progress

#1972 Streamline logic of create_distribution_table utility and improve tbi fuzzing
  taxcalc/taxcalcio.py
  taxcalc/tbi/tbi_utils.py
  taxcalc/tests/tbi_cps_expect.txt
  taxcalc/tests/tbi_puf_expect.txt
  taxcalc/tests/test_tbi.py
  taxcalc/tests/test_utils.py
  taxcalc/utils.py
Labels: ready

#1973 Streamline logic of create_difference_table utility and improve tbi fuzzing
  taxcalc/tests/tbi_cps_expect.txt
  taxcalc/tests/tbi_puf_expect.txt
  taxcalc/tests/test_calculate.py
  taxcalc/tests/test_utils.py
  taxcalc/utils.py
  taxcalc/utilsprvt.py
Labels: ready

#1974 Check in create_difference_table utility function that DataFrames are in same order
  taxcalc/tbi/tbi_utils.py
  taxcalc/tests/test_utils.py
  taxcalc/utils.py
Labels: in progress

#1976 Restrict fuzzing to reform-affected filing units
  taxcalc/tbi/tbi.py
  taxcalc/tbi/tbi_utils.py
  taxcalc/tests/tbi_cps_expect.txt
  taxcalc/tests/tbi_puf_expect.txt
Labels: ready

#1978 Update user documentation and cookbook for Tax-Calculator version 0.19.0
  docs/cookbook.html
  docs/index.html
  docs/index.htmx
Labels: in progress

#1979 Refactor fuzzing logic
  taxcalc/calculate.py
  taxcalc/tbi/tbi.py
  taxcalc/tbi/tbi_utils.py
  taxcalc/tests/tbi_puf_expect.txt
  taxcalc/tests/test_tbi.py
  taxcalc/tests/test_utils.py
  taxcalc/utils.py
Labels: ready

#1982 Fix bug reported in issue #1980
  taxcalc/parameters.py
  taxcalc/tests/test_parameters.py
  taxcalc/tests/test_policy.py
Labels: ready

#1984 Simplify table-creation Calculator methods and related utility functions
  taxcalc/calculate.py
  taxcalc/parameters.py
  taxcalc/reforms/2017_law.out
  taxcalc/reforms/BrownKhanna.out
  taxcalc/reforms/Clinton2016.out
  taxcalc/reforms/Renacci.out
  taxcalc/reforms/RyanBrady.out
  taxcalc/reforms/TCJA_House.out
  taxcalc/reforms/TCJA_House_Amended.out
  taxcalc/reforms/TCJA_Reconciliation.out
  taxcalc/reforms/TCJA_Senate.out
  taxcalc/reforms/TCJA_Senate_111417.out
  taxcalc/reforms/TCJA_Senate_120117.out
  taxcalc/reforms/Trump2016.out
  taxcalc/reforms/Trump2017.out
  taxcalc/reforms/clp.out
  taxcalc/reforms/ptaxes0.out
  taxcalc/reforms/ptaxes1.out
  taxcalc/reforms/ptaxes2.out
  taxcalc/reforms/ptaxes3.out
  taxcalc/tbi/tbi_utils.py
  taxcalc/tests/tbi_cps_expect.txt
  taxcalc/tests/test_calculate.py
  taxcalc/tests/test_reforms.py
  taxcalc/tests/test_utils.py
  taxcalc/utils.py
Labels: ready

#1985 Add no_benefits=False optional argument to Records.cps_constructor
  taxcalc/records.py
  taxcalc/tests/test_behavior.py
  taxcalc/tests/test_calculate.py
  taxcalc/tests/test_compatible_data.py
  taxcalc/tests/test_consumption.py
  taxcalc/tests/test_macro_elasticity.py
  taxcalc/tests/test_utils.py
Labels: in progress

#1987 Cherrypick code changes from closed PR #1986
  taxcalc/functions.py
  taxcalc/records.py
  taxcalc/taxcalcio.py
  taxcalc/tests/conftest.py
  taxcalc/tests/test_calculate.py
  taxcalc/tests/test_compatible_data.py
  taxcalc/tests/test_cpscsv.py
  taxcalc/tests/test_pufcsv.py
  taxcalc/tests/test_records.py
  taxcalc/tests/test_tbi.py
  taxcalc/tests/test_utils.py
  taxcalc/utils.py
Labels: ready
